#!/bin/bash
# Author: Guillermo Robles
#
# Convert nips from the given file or the standard input

DB_LOCATION='/usr/share/humans/humans.db'
if [ ! -f "${DB_LOCATION}" ]; then
    DB_LOCATION='./humans.db'
fi

if [[ "$1" = "" ]]; then
    FILE=/dev/stdin
else
    FILE="$1"
fi

while read line; do
    username=$(echo "$line" | sed 's/.*\([0-9]\{6\}\).*/\1/')
    realname=$(sqlite3 "${DB_LOCATION}" "SELECT name FROM STUDENT WHERE nip='${username}'")
    if [ "$realname" == "" ]; then
        echo "$line"
    else
        echo "$line ($realname)"
    fi
done < "$FILE"
