#!/bin/bash
# Author: Guillermo Robles
#
# Convert nips from the given file or the standard input

DB_LOCATION='/usr/share/humans/humans.db'
if [ ! -f "${DB_LOCATION}" ]; then
    DB_LOCATION='./humans.db'
fi

if [[ "$1" = "" ]]; then
    FILE=/dev/stdin
else
    FILE="$1"
    if file "${FILE}" | grep -q "PDF document"; then
        # The passed file is a pdf
        PDF_FILE="True"
        echo "${FILE}"
    fi
fi

# $1 - Line to process
process_line () {
    username=$(echo "$1" | sed 's/.*\([0-9]\{6\}\).*/\1/')
    realname=$(sqlite3 "${DB_LOCATION}" "SELECT name FROM STUDENT WHERE nip='${username}'")
    if [ "$realname" == "" ]; then
        echo "$1"
    else
        echo "$1 ($realname)"
    fi
}

if [ ! -z "${PDF_FILE+x}" ]; then
    # Process as PDF
    pdfgrep '^.*' "${FILE}" |
        while read line; do
            process_line "${line}"
        done
else
    cat "${FILE}" |
        while read line; do
            process_line "${line}"
        done
fi
